# Generated by Django 3.2.7 on 2022-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220115_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='predicted',
            field=models.FloatField(default=0.0),
        ),
    ]
